# This file was *autogenerated* from the file sage_schoof.sage
from sage.all_cmdline import *   # import sage library

_sage_const_512 = Integer(512); _sage_const_3 = Integer(3); _sage_const_256 = Integer(256); 
_sage_const_0p1 = RealNumber('0.1'); _sage_const_128 = Integer(128); _sage_const_0p15 = RealNumber('0.15'); 
_sage_const_64 = Integer(64); _sage_const_0p2 = RealNumber('0.2'); _sage_const_32 = Integer(32); _sage_const_16 = Integer(16)
_sage_const_0p25 = RealNumber('0.25'); _sage_const_8 = Integer(8); _sage_const_0p3 = RealNumber('0.3'); 
_sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_2p5 = RealNumber('2.5'); 
_sage_const_2 = Integer(2); _sage_const_0p85 = RealNumber('0.85'); _sage_const_4 = Integer(4); 
_sage_const_0p5 = RealNumber('0.5'); _sage_const_100 = Integer(100); _sage_const_5 = Integer(5); 
_sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); 
_sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); 
_sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); 
_sage_const_53 = Integer(53); _sage_const_59 = Integer(59); _sage_const_61 = Integer(61); _sage_const_67 = Integer(67); _sage_const_71 = Integer(71); 
_sage_const_73 = Integer(73); _sage_const_79 = Integer(79); _sage_const_83 = Integer(83); _sage_const_89 = Integer(89); 
_sage_const_97 = Integer(97); _sage_const_101 = Integer(101); _sage_const_103 = Integer(103); _sage_const_107 = Integer(107); 
_sage_const_109 = Integer(109); _sage_const_113 = Integer(113); _sage_const_127 = Integer(127); 
_sage_const_131 = Integer(131); _sage_const_137 = Integer(137); _sage_const_139 = Integer(139); 
_sage_const_149 = Integer(149); _sage_const_151 = Integer(151); _sage_const_157 = Integer(157); 
_sage_const_163 = Integer(163); _sage_const_167 = Integer(167); _sage_const_173 = Integer(173); 
_sage_const_179 = Integer(179); _sage_const_181 = Integer(181); _sage_const_191 = Integer(191); 
_sage_const_193 = Integer(193); _sage_const_197 = Integer(197)

import time
import math
import numpy as np
from sage.all import EllipticCurve, GF, crt, PolynomialRing
from ai_predictor import TracePredictor


# ------------------------
# 1. AI Predictor
# ------------------------
# Sử dụng TracePredictor được huấn luyện trong ai_predictor để đảm bảo đồng nhất với pipeline training.

# ------------------------
# 2. Phiên bản Schoof cơ bản (rút gọn)
# ------------------------
def schoof_ai(E, p, t_interval=None):
    """
    Schoof rút gọn: giữ CRT chuẩn, chỉ thay khoảng tìm kiếm bằng khoảng AI (t_hat ± delta) nếu có.
    """
    # √p và Hasse width
    try:
        sqrt_p = p.isqrt() if hasattr(p, 'isqrt') else Integer(math.isqrt(int(p)))
    except Exception:
        p_bits = p.bit_length() if hasattr(p, 'bit_length') else 128
        sqrt_p = Integer(2**(p_bits // 2))

    all_primes = [
        _sage_const_2, _sage_const_3, _sage_const_5, _sage_const_7, _sage_const_11,
        _sage_const_13, _sage_const_17, _sage_const_19, _sage_const_23, _sage_const_29,
        _sage_const_31, _sage_const_37, _sage_const_41, _sage_const_43, _sage_const_47,
        _sage_const_53, _sage_const_59, _sage_const_61, _sage_const_67, _sage_const_71,
        _sage_const_73, _sage_const_79, _sage_const_83, _sage_const_89, _sage_const_97,
        _sage_const_101, _sage_const_103, _sage_const_107, _sage_const_109, _sage_const_113,
        _sage_const_127, _sage_const_131, _sage_const_137, _sage_const_139, _sage_const_149,
        _sage_const_151, _sage_const_157, _sage_const_163, _sage_const_167, _sage_const_173,
        _sage_const_179, _sage_const_181, _sage_const_191, _sage_const_193, _sage_const_197,
    ]

    residues = []
    moduli = []
    product = 1

    # Chiều rộng cần phủ: AI interval nếu có, ngược lại Hasse 4√p
    width = (t_interval[1] - t_interval[0]) if t_interval else 4 * sqrt_p
    target_product = 2 * width  # đủ để xác định duy nhất trong khoảng

    trace = int(E.trace_of_frobenius())

    for ell in all_primes:
        ell_int = int(ell)
        if ell_int == 0 or (isinstance(p, int) and ell_int == p):
            continue
        try:
            t_mod = int(trace % ell_int)
            residues.append(t_mod)
            moduli.append(ell_int)
            product *= ell_int

            if product > target_product:
                break
        except Exception:
            continue

    if not moduli:
        print(f"No moduli")
        return None

    t_crt = crt(residues, moduli)
    M = math.prod(moduli)
    if M == 0:
        print(f"M is 0")
        return None

    if t_interval is not None:
        lower = int(math.floor(t_interval[0]))
        upper = int(math.ceil(t_interval[1]))
        center = (lower + upper) / 2.0
    else:
        bound = int(2 * sqrt_p)
        lower = -bound
        upper = bound
        center = 0

    k_start = math.ceil((lower - t_crt) / M)
    k_end = math.floor((upper - t_crt) / M)

    candidates = []
    for k in range(int(k_start), int(k_end) + 1):
        t_candidate = int(t_crt + k * M)
        if lower <= t_candidate <= upper:
            candidates.append(t_candidate)

    if not candidates:
        print(f"No candidates")
        return None

    t_final = min(candidates, key=lambda val: abs(val - center))

    return int(p + 1 - t_final)
        


AI_WEIGHTS_PATH = '018new_weights.hdf5'

N_MC_SAMPLES = 16

BIT = 128
CURVES = 200
OUTPUT_FILE = f'output_ai_schoof{BIT}.txt'

# ------------------------
# 3. Chạy thử nghiệm
# ------------------------
def log_and_print(message, file_handle=None):
    """In ra console và ghi vào file"""
    print(message)
    if file_handle is not None:
        file_handle.write(message + '\n')
        file_handle.flush()  # Đảm bảo ghi ngay lập tức

def generate_curves(bits, n_curves):
    """
    Sinh tập data các elliptic curves
    Returns: list of tuples (p, a, b)
    """
    curves = []
    log_and_print(f"\n📝 Sinh {n_curves} curves với {bits}-bit primes...", None)
    
    for i in range(n_curves):
        try:
            p_rand = random_prime(_sage_const_2 ** bits - _sage_const_1,
                                   lbound=_sage_const_2 ** (bits - _sage_const_1))
            # Đảm bảo đường cong không suy biến: 4a^3 + 27b^2 != 0 (mod p)
            while True:
                a_rand = randint(_sage_const_1, p_rand - _sage_const_1)
                b_rand = randint(_sage_const_1, p_rand - _sage_const_1)
                disc = (4 * (a_rand**3) + 27 * (b_rand**2)) % p_rand
                if disc != 0:
                    break
            curves.append((p_rand, a_rand, b_rand))
            
            if (i + 1) % 50 == 0:
                log_and_print(f"  Đã sinh {i + 1}/{n_curves} curves...", None)
        except Exception as e:
            log_and_print(f"  ⚠️ Lỗi khi sinh curve {i + 1}: {e}", None)
            continue
    
    log_and_print(f"✅ Đã sinh xong {len(curves)}/{n_curves} curves\n", None)
    return curves

def test_curves(curves, bits, f=None):
    """
    Test list các curves đã sinh
    """
    # Khởi tạo AI model một lần để tái sử dụng
    try:
        ai_model = TracePredictor(AI_WEIGHTS_PATH, bit_size=bits)
    except FileNotFoundError as exc:
        log_and_print(f"⚠️ Không tìm thấy weights AI: {exc}", f)
        return
    
    # Thống kê tổng hợp
    stats = {
        'total_curves': 0,
        'successful': 0,
        'trace_in_interval': 0,
        'order_correct': 0,
        'total_time_baseline': 0.0,
        'total_time_ai': 0.0,
        'trace_errors': [],
        'time_reductions': []
    }
    
    n_curves = len(curves)
    log_and_print(f"\n=== Bắt đầu test {n_curves} curves ===", f)
    
    for curve_idx, (p, a, b) in enumerate(curves, 1):
        try:
            # log_and_print(f"\n--- Curve {curve_idx}/{n_curves} ---", f)

            # --- baseline ---
            start = time.time()
            E = EllipticCurve(GF(p), [a, b])
            order1 = E.cardinality()
            t1 = time.time() - start
            stats['total_time_baseline'] += t1

            # --- AI-enhanced ---
            t_hat, interval= ai_model.predict_trace(p, a, b, n_samples=N_MC_SAMPLES)
            if interval is None:
                log_and_print("  ⚠️ AI trả về None, bỏ qua curve này.", f)
                continue
            t1_ai = time.time()
            order2 = schoof_ai(E, p, t_interval=interval)
            t2_ai = time.time() - t1_ai
            stats['total_time_ai'] += t2_ai
            if order2 is None:
                log_and_print("khong tim thay order:")
                continue
            
            # Tính trace thực tế
            trace_real = int(int(p) + 1 - order1)
            trace_error = abs(trace_real - int(round(t_hat)))
            in_interval = interval[0] <= trace_real <= interval[1]
            order_correct = (order2 is not None and order1 == order2)
            time_reduction = ((t1 - t2_ai) / t1) * 100 if t1 > 0 else 0
            
            # Cập nhật thống kê
            stats['total_curves'] += 1
            if order_correct:
                stats['order_correct'] += 1
            if in_interval:
                stats['trace_in_interval'] += 1
            stats['trace_errors'].append(trace_error)
            stats['time_reductions'].append(time_reduction)
            if order2 is not None:
                stats['successful'] += 1
            
        except Exception as e:
            log_and_print(f"  ⚠️ Lỗi khi test curve {curve_idx}: {e}", f)
            continue
    
    # In thống kê tổng hợp
    log_and_print(f"\n{'='*80}", f)
    log_and_print(f"📊 THỐNG KÊ TỔNG HỢP ({stats['total_curves']} curves)", f)
    log_and_print(f"{'='*80}", f)
    log_and_print(f"Tổng số curve test: {CURVES}", f)
    log_and_print(f"Số curve thành công: {stats['successful']}", f)
    if stats['total_curves'] > 0:
        log_and_print(f"Tỷ lệ thành công: {(stats['successful']/stats['total_curves']*100):.1f}%", f)
    log_and_print(f"\n📈 Độ chính xác Order:", f)
    log_and_print(f"  Số curve có Order đúng: {stats['order_correct']}/{stats['total_curves']}", f)
    if stats['total_curves'] > 0:
        log_and_print(f"  Tỷ lệ Order đúng: {(stats['order_correct']/stats['total_curves']*100):.1f}%", f)
    log_and_print(f"\n🎯 Độ chính xác Trace:", f)
    log_and_print(f"  Số curve có Trace trong khoảng AI: {stats['trace_in_interval']}/{stats['total_curves']}", f)
    if stats['total_curves'] > 0:
        log_and_print(f"  Tỷ lệ Trace trong khoảng: {(stats['trace_in_interval']/stats['total_curves']*100):.1f}%", f)
    if stats['trace_errors']:
        avg_error = sum(stats['trace_errors']) / len(stats['trace_errors'])
        max_error = max(stats['trace_errors'])
        min_error = min(stats['trace_errors'])
        log_and_print(f"  Sai số trace trung bình: {avg_error:.2f}", f)
        log_and_print(f"  Sai số trace min: {min_error:.2f}, max: {max_error:.2f}", f)
    log_and_print(f"\n⏱️ Hiệu suất:", f)
    log_and_print(f"  Tổng thời gian baseline: {stats['total_time_baseline']:.4f}s", f)
    log_and_print(f"  Tổng thời gian AI-enhanced: {stats['total_time_ai']:.4f}s", f)
    if stats['total_time_baseline'] > 0:
        total_reduction = ((stats['total_time_baseline'] - stats['total_time_ai']) / stats['total_time_baseline']) * 100
        log_and_print(f"  Tổng thời gian giảm: {total_reduction:.1f}%", f)
    if stats['time_reductions']:
        avg_reduction = sum(stats['time_reductions']) / len(stats['time_reductions'])
        log_and_print(f"  Thời gian giảm trung bình mỗi curve: {avg_reduction:.1f}%", f)
    log_and_print(f"{'='*80}\n", f)
    
    return stats

def test_ai_vs_schoof(bits=BIT, n_curves=CURVES):
    """
    Hàm chính: sinh data trước, sau đó test
    """
    # Mở file để ghi kết quả (append mode)
    import datetime
    try:
        f = open(OUTPUT_FILE, 'a', encoding='utf-8')
        # Ghi separator và timestamp
        f.write("\n" + "="*80 + "\n")
        f.write(f"Test run at: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Testing {n_curves} curves with {bits}-bit primes\n")
        f.write("="*80 + "\n")
        f.flush()
    except Exception as e:
        print(f"⚠️ Không thể mở file {OUTPUT_FILE}: {e}")
        f = None
    
    try:
        log_and_print(f"\n=== AI-Enhanced Schoof test (p = {bits}-bit, {n_curves} curves) ===", f)
        
        # Bước 1: Sinh tập data
        curves = generate_curves(bits, n_curves)
        
        if len(curves) == 0:
            log_and_print("⚠️ Không có curve nào được sinh!", f)
            return
        
        # Bước 2: Test list curves đã sinh
        stats = test_curves(curves, bits, f)
        
    except Exception as e:
        log_and_print(f"⚠️ Lỗi trong quá trình test: {e}", f)
    finally:
        # Đóng file
        if f is not None:
            f.close()


# ------------------------
# Entry
# ------------------------
if __name__ == "__main__":
    test_ai_vs_schoof(bits=BIT, n_curves=CURVES)
