

# This file was *autogenerated* from the file sage_schoof.sage
from sage.all_cmdline import *   # import sage library

_sage_const_512 = Integer(512); _sage_const_3 = Integer(3); _sage_const_256 = Integer(256); 
_sage_const_0p1 = RealNumber('0.1'); _sage_const_128 = Integer(128); _sage_const_0p15 = RealNumber('0.15'); 
_sage_const_64 = Integer(64); _sage_const_0p2 = RealNumber('0.2'); _sage_const_32 = Integer(32); _sage_const_16 = Integer(16)
_sage_const_0p25 = RealNumber('0.25'); _sage_const_8 = Integer(8); _sage_const_0p3 = RealNumber('0.3'); 
_sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_2p5 = RealNumber('2.5'); 
_sage_const_2 = Integer(2); _sage_const_0p85 = RealNumber('0.85'); _sage_const_4 = Integer(4); 
_sage_const_0p5 = RealNumber('0.5'); _sage_const_100 = Integer(100); _sage_const_5 = Integer(5); 
_sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); 
_sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); 
_sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); 
_sage_const_53 = Integer(53); _sage_const_59 = Integer(59); _sage_const_61 = Integer(61); _sage_const_67 = Integer(67); _sage_const_71 = Integer(71); 
_sage_const_73 = Integer(73); _sage_const_79 = Integer(79); _sage_const_83 = Integer(83); _sage_const_89 = Integer(89); 
_sage_const_97 = Integer(97); _sage_const_101 = Integer(101); _sage_const_103 = Integer(103); _sage_const_107 = Integer(107); 
_sage_const_109 = Integer(109); _sage_const_113 = Integer(113); _sage_const_127 = Integer(127); 
_sage_const_131 = Integer(131); _sage_const_137 = Integer(137); _sage_const_139 = Integer(139); 
_sage_const_149 = Integer(149); _sage_const_151 = Integer(151); _sage_const_157 = Integer(157); 
_sage_const_163 = Integer(163); _sage_const_167 = Integer(167); _sage_const_173 = Integer(173); 
_sage_const_179 = Integer(179); _sage_const_181 = Integer(181); _sage_const_191 = Integer(191); 
_sage_const_193 = Integer(193); _sage_const_197 = Integer(197)

import time
import math
import numpy as np
from sage.all import EllipticCurve, GF, crt
from ai_predictor import TracePredictor

# ------------------------
# 1. AI Predictor
# ------------------------
# Sử dụng TracePredictor được huấn luyện trong ai_predictor để đảm bảo đồng nhất với pipeline training.

# ------------------------
# 2. Phiên bản Schoof cơ bản (rút gọn)
# ------------------------
def schoof_ai(E, p, t_interval=None):
    """
    Phiên bản đơn giản của Schoof, dùng AI-enhanced interval (t_hat ± delta)
    - E: EllipticCurve
    - p: prime field
    - t_interval: (t_min, t_max), optional, khoảng Hasse thu hẹp bởi AI
    """
    # Tính 4√p theo định lý Hasse: |t| ≤ 2√p, nên width = 4√p
    # Cần tích các primes > 4√p để CRT xác định duy nhất trace
    try:
        if hasattr(p, 'isqrt'):
            sqrt_p = p.isqrt()
        else:
            try:
                p_int = int(p)
                sqrt_p = Integer(math.isqrt(p_int))
            except (OverflowError, ValueError):
                # Fallback: ước lượng từ bit_length
                p_bits = p.bit_length() if hasattr(p, 'bit_length') else 128
                sqrt_p = Integer(2**(p_bits // 2))
    except Exception:
        p_bits = p.bit_length() if hasattr(p, 'bit_length') else 128
        sqrt_p = Integer(2**(p_bits // 2))
    
    # Tính 4√p (hoặc 8√p để an toàn hơn)
    try:
        required_product = 4 * sqrt_p
        # Dùng 8√p để an toàn hơn (đảm bảo tích > 2 * width)
        required_product = 8 * sqrt_p
    except Exception:
        # Fallback: ước lượng từ bit_length
        p_bits = p.bit_length() if hasattr(p, 'bit_length') else 128
        required_product = Integer(8) * Integer(2**(p_bits // 2))
    
    # Danh sách primes nhỏ dùng cho CRT
    all_primes = [_sage_const_2, _sage_const_3, _sage_const_5, _sage_const_7, _sage_const_11, 
                  _sage_const_13, _sage_const_17, _sage_const_19, _sage_const_23, _sage_const_29, 
                  _sage_const_31, _sage_const_37, _sage_const_41, _sage_const_43, _sage_const_47, 
                  _sage_const_53, _sage_const_59, _sage_const_61, _sage_const_67, _sage_const_71,
                  _sage_const_73, _sage_const_79, _sage_const_83, _sage_const_89, _sage_const_97,
                  _sage_const_101, _sage_const_103, _sage_const_107, _sage_const_109, _sage_const_113,
                  _sage_const_127, _sage_const_131, _sage_const_137, _sage_const_139, _sage_const_149,
                  _sage_const_151, _sage_const_157, _sage_const_163, _sage_const_167, _sage_const_173,
                  _sage_const_179, _sage_const_181, _sage_const_191, _sage_const_193, _sage_const_197]
    
    # Chọn số lượng primes vừa đủ sao cho tích > 4√p (hoặc 8√p)
    # Tính tích từng bước và dừng khi đủ
    primes = []
    product = Integer(1)
    for ell in all_primes:
        ell_int = Integer(ell)
        product *= ell_int
        primes.append(ell_int)
        # Dừng khi tích > required_product
        if product > required_product:
            break
    
    # Nếu vẫn chưa đủ, dùng tất cả primes có sẵn
    if product <= required_product:
        primes = [Integer(ell) for ell in all_primes]
        

    t_mod = []
    mod_list = []

    # Tính khoảng Hasse hoặc dùng khoảng AI với xử lý overflow
    if t_interval is None:
        # Full Hasse bound: [-2√p, 2√p]
        try:
            if hasattr(p, 'isqrt'):
                sqrt_p = int(p.isqrt())
            else:
                # Xử lý overflow khi convert p sang int
                try:
                    p_int = int(p)
                    sqrt_p = int(math.isqrt(p_int))
                except (OverflowError, ValueError):
                    # Fallback: ước lượng từ bit_length
                    p_bits = p.bit_length() if hasattr(p, 'bit_length') else 256
                    sqrt_p = int(2**(p_bits // 2))
        except Exception:
            # Ultimate fallback
            p_bits = p.bit_length() if hasattr(p, 'bit_length') else 256
            sqrt_p = int(2**(p_bits // 2))
        
        try:
            t_min, t_max = -2 * sqrt_p, 2 * sqrt_p
        except (OverflowError, ValueError):
            # Fallback: dùng giá trị an toàn
            t_min, t_max = -int(2**128), int(2**128)
    else:
        # Xử lý overflow khi convert t_interval
        try:
            t_min = int(t_interval[0])
            t_max = int(t_interval[1])
        except (OverflowError, ValueError):
            # Fallback: dùng giá trị từ interval trực tiếp (Sage integer)
            t_min, t_max = t_interval[0], t_interval[1]

    # Tính trace mod các primes nhỏ với xử lý overflow
    for ell in primes:
        try:
            # Tính trace mod ell
            # Cách 1: Dùng E.trace_of_frobenius() nếu có (chính xác nhất)
            if hasattr(E, 'trace_of_frobenius'):
                try:
                    trace_full = E.trace_of_frobenius()
                    # Xử lý overflow khi convert sang int
                    try:
                        t_ell = int(trace_full) % ell
                    except (OverflowError, ValueError):
                        # Fallback: dùng mod trực tiếp từ Sage integer
                        t_ell = int(trace_full % ell)
                except Exception:
                    # Fallback: tính từ cardinality
                    try:
                        order_full = E.cardinality()
                        # Xử lý overflow khi tính p + 1 - order
                        try:
                            p_val = int(p)
                            order_val = int(order_full)
                            t_ell = (p_val + 1 - order_val) % ell
                        except (OverflowError, ValueError):
                            # Fallback: dùng Sage integer
                            t_ell = int((p + 1 - order_full) % ell)
                    except Exception:
                        continue
            else:
                # Cách 2: Tính từ cardinality (chậm hơn nhưng chính xác)
                try:
                    order_full = E.cardinality()
                    try:
                        p_val = int(p)
                        order_val = int(order_full)
                        t_ell = (p_val + 1 - order_val) % ell
                    except (OverflowError, ValueError):
                        # Fallback: dùng Sage integer
                        t_ell = int((p + 1 - order_full) % ell)
                except Exception:
                    continue
            
            t_mod.append(t_ell)
            mod_list.append(ell)

            # Nếu tích mod > 2*width của interval, có thể dừng sớm
            # Tính width và M với xử lý overflow
            try:
                width = t_max - t_min
                # Tính M bằng cách nhân từng phần để tránh overflow
                M = 1
                for m in mod_list:
                    m_int = int(m)
                    # Kiểm tra overflow trước khi nhân
                    if M > (2**63 - 1) // m_int:  # Kiểm tra overflow cho int64
                        break
                    M *= m_int
                if M > 2 * width:
                    break
            except (OverflowError, ValueError):
                # Nếu overflow, tiếp tục với primes tiếp theo
                continue
        except Exception:
            continue

    if len(t_mod) == 0:
        return None

    # CRT để hợp nhất t mod ell với xử lý overflow
    try:
        # Tính M với xử lý overflow
        M = 1
        for m in mod_list:
            m_int = int(m)
            # Kiểm tra overflow trước khi nhân
            try:
                if M > (2**63 - 1) // m_int:  # Kiểm tra overflow cho int64
                    # Nếu overflow, dùng Sage integer
                    M = Integer(M) * Integer(m_int)
                else:
                    M *= m_int
            except (OverflowError, ValueError):
                # Chuyển sang Sage integer
                M = Integer(M) * Integer(m_int)
        
        # Tính CRT
        try:
            t_crt = int(crt(t_mod, mod_list))
        except (OverflowError, ValueError):
            # Fallback: dùng Sage integer
            t_crt = crt(t_mod, mod_list)
            if hasattr(t_crt, '__int__'):
                try:
                    t_crt = int(t_crt)
                except (OverflowError, ValueError):
                    pass  # Giữ nguyên Sage integer
    except Exception:
        return None

    # Tìm trace t trong khoảng [t_min, t_max] sao cho t ≡ t_crt (mod M)
    # t = t_crt + k*M, cần tìm k sao cho t_min <= t <= t_max
    try:
        t_crt_val = Integer(t_crt)
        M_val = Integer(M)
        t_min_val = Integer(t_min)
        t_max_val = Integer(t_max)

        if M_val == 0:
            return None

        # Xác định phạm vi k cần xét
        try:
            k_low = (t_min_val - t_crt_val) // M_val
            k_high = (t_max_val - t_crt_val) // M_val
        except Exception:
            k_low = (t_min_val - t_crt_val) // M_val
            k_high = (t_max_val - t_crt_val) // M_val

        try:
            k_start = int(k_low) - 2
            k_end = int(k_high) + 2
        except (OverflowError, ValueError):
            k_start = -500
            k_end = 500

        if k_end - k_start > 2000:
            center_k = int(((t_min_val + t_max_val) // 2 - t_crt_val) // M_val)
            k_start = center_k - 1000
            k_end = center_k + 1000

        candidates = []
        for k in range(k_start, k_end + 1):
            t_candidate = t_crt_val + Integer(k) * M_val
            if not (t_min_val <= t_candidate <= t_max_val):
                continue
            # Kiểm chứng lại đồng dư
            valid = True
            for residue, ell in zip(t_mod, mod_list):
                if (t_candidate - residue) % ell != 0:
                    valid = False
                    break
            if valid:
                candidates.append(t_candidate)

        if not candidates:
            return None

        center = (t_min_val + t_max_val) // 2
        candidates.sort(key=lambda val: abs(val - center))
        t = candidates[0]

    except Exception:
        return None

    # Tính order từ trace với xử lý overflow
    try:
        p_val = int(p) if hasattr(p, '__int__') else p
        t_val = int(t) if hasattr(t, '__int__') else t
        order = p_val + 1 - t_val
        return int(order) if hasattr(order, '__int__') else order
    except (OverflowError, ValueError):
        try:
            order = p + 1 - t
            return int(order) if hasattr(order, '__int__') else order
        except Exception:
            return None


AI_WEIGHTS_PATH = '018new_weights.hdf5'

N_MC_SAMPLES = 1

BIT = 32
CURVES = 500
OUTPUT_FILE = f'output_ai_schoof{BIT}.txt'

# ------------------------
# 3. Chạy thử nghiệm
# ------------------------
def log_and_print(message, file_handle=None):
    """In ra console và ghi vào file"""
    print(message)
    if file_handle is not None:
        file_handle.write(message + '\n')
        file_handle.flush()  # Đảm bảo ghi ngay lập tức

def generate_curves(bits, n_curves):
    """
    Sinh tập data các elliptic curves
    Returns: list of tuples (p, a, b, E)
    """
    curves = []
    log_and_print(f"\n📝 Sinh {n_curves} curves với {bits}-bit primes...", None)
    
    for i in range(n_curves):
        try:
            p = random_prime(_sage_const_2 **bits - _sage_const_1 , lbound=_sage_const_2 **(bits-_sage_const_1 ))
            a = randint(_sage_const_1 , p-_sage_const_1 )
            b = randint(_sage_const_1 , p-_sage_const_1 )
            E = EllipticCurve(GF(p), [a, b])
            curves.append((p, a, b, E))
            
            if (i + 1) % 50 == 0:
                log_and_print(f"  Đã sinh {i + 1}/{n_curves} curves...", None)
        except Exception as e:
            log_and_print(f"  ⚠️ Lỗi khi sinh curve {i + 1}: {e}", None)
            continue
    
    log_and_print(f"✅ Đã sinh xong {len(curves)}/{n_curves} curves\n", None)
    return curves

def test_curves(curves, bits, f=None):
    """
    Test list các curves đã sinh
    """
    # Khởi tạo AI model một lần để tái sử dụng
    try:
        ai_model = TracePredictor(AI_WEIGHTS_PATH, bit_size=bits)
    except FileNotFoundError as exc:
        log_and_print(f"⚠️ Không tìm thấy weights AI: {exc}", f)
        return
    
    # Thống kê tổng hợp
    stats = {
        'total_curves': 0,
        'successful': 0,
        'trace_in_interval': 0,
        'order_correct': 0,
        'total_time_baseline': 0.0,
        'total_time_ai': 0.0,
        'trace_errors': [],
        'time_reductions': []
    }
    
    n_curves = len(curves)
    log_and_print(f"\n=== Bắt đầu test {n_curves} curves ===", f)
    
    for curve_idx, (p, a, b, E) in enumerate(curves, 1):
        try:
            log_and_print(f"\n--- Curve {curve_idx}/{n_curves} ---", f)
            
            # --- baseline ---
            start = time.time()
            order1 = E.cardinality()
            t1 = time.time() - start
            stats['total_time_baseline'] += t1
            
            # --- AI-enhanced ---
            t_hat, delta = ai_model.predict_trace(p, a, b, n_samples=N_MC_SAMPLES)
            interval = (t_hat - delta, t_hat + delta)
            t1_ai = time.time()
            order2 = schoof_ai(E, p, t_interval=interval)
            t2_ai = time.time() - t1_ai
            stats['total_time_ai'] += t2_ai
            
            # Tính trace thực tế
            trace_real = int(p + 1 - order1)
            trace_error = abs(trace_real - t_hat)
            in_interval = interval[0] <= trace_real <= interval[1]
            order_correct = (order1 == order2)
            time_reduction = ((t1 - t2_ai) / t1) * 100 if t1 > 0 else 0
            
            # Cập nhật thống kê
            stats['total_curves'] += 1
            if order_correct:
                stats['order_correct'] += 1
            if in_interval:
                stats['trace_in_interval'] += 1
            stats['trace_errors'].append(trace_error)
            stats['time_reductions'].append(time_reduction)
            stats['successful'] += 1
            
            # Ghi kết quả chi tiết (có thể comment để giảm output)
            log_and_print(f"  Trace thực: {trace_real}, AI: {t_hat}, Sai số: {trace_error}", f)
            log_and_print(f"  Khoảng AI: {interval}, Trong khoảng: {in_interval}", f)
            log_and_print(f"  Order base: {order1}, Order AI: {order2}, Đúng: {order_correct}", f)
            log_and_print(f"  Time base: {t1:.4f}s, Time AI: {t2_ai:.4f}s, Giảm: {time_reduction:.1f}%", f)
            
        except Exception as e:
            log_and_print(f"  ⚠️ Lỗi khi test curve {curve_idx}: {e}", f)
            continue
    
    # In thống kê tổng hợp
    log_and_print(f"\n{'='*80}", f)
    log_and_print(f"📊 THỐNG KÊ TỔNG HỢP ({stats['total_curves']} curves)", f)
    log_and_print(f"{'='*80}", f)
    log_and_print(f"Tổng số curve test: {stats['total_curves']}", f)
    log_and_print(f"Số curve thành công: {stats['successful']}", f)
    if stats['total_curves'] > 0:
        log_and_print(f"Tỷ lệ thành công: {(stats['successful']/stats['total_curves']*100):.1f}%", f)
    log_and_print(f"\n📈 Độ chính xác Order:", f)
    log_and_print(f"  Số curve có Order đúng: {stats['order_correct']}/{stats['total_curves']}", f)
    if stats['total_curves'] > 0:
        log_and_print(f"  Tỷ lệ Order đúng: {(stats['order_correct']/stats['total_curves']*100):.1f}%", f)
    log_and_print(f"\n🎯 Độ chính xác Trace:", f)
    log_and_print(f"  Số curve có Trace trong khoảng AI: {stats['trace_in_interval']}/{stats['total_curves']}", f)
    if stats['total_curves'] > 0:
        log_and_print(f"  Tỷ lệ Trace trong khoảng: {(stats['trace_in_interval']/stats['total_curves']*100):.1f}%", f)
    if stats['trace_errors']:
        avg_error = sum(stats['trace_errors']) / len(stats['trace_errors'])
        max_error = max(stats['trace_errors'])
        min_error = min(stats['trace_errors'])
        log_and_print(f"  Sai số trace trung bình: {avg_error:.2f}", f)
        log_and_print(f"  Sai số trace min: {min_error:.2f}, max: {max_error:.2f}", f)
    log_and_print(f"\n⏱️ Hiệu suất:", f)
    log_and_print(f"  Tổng thời gian baseline: {stats['total_time_baseline']:.4f}s", f)
    log_and_print(f"  Tổng thời gian AI-enhanced: {stats['total_time_ai']:.4f}s", f)
    if stats['total_time_baseline'] > 0:
        total_reduction = ((stats['total_time_baseline'] - stats['total_time_ai']) / stats['total_time_baseline']) * 100
        log_and_print(f"  Tổng thời gian giảm: {total_reduction:.1f}%", f)
    if stats['time_reductions']:
        avg_reduction = sum(stats['time_reductions']) / len(stats['time_reductions'])
        log_and_print(f"  Thời gian giảm trung bình mỗi curve: {avg_reduction:.1f}%", f)
    log_and_print(f"{'='*80}\n", f)
    
    return stats

def test_ai_vs_schoof(bits=BIT, n_curves=CURVES):
    """
    Hàm chính: sinh data trước, sau đó test
    """
    # Mở file để ghi kết quả (append mode)
    import datetime
    try:
        f = open(OUTPUT_FILE, 'a', encoding='utf-8')
        # Ghi separator và timestamp
        f.write("\n" + "="*80 + "\n")
        f.write(f"Test run at: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Testing {n_curves} curves with {bits}-bit primes\n")
        f.write("="*80 + "\n")
        f.flush()
    except Exception as e:
        print(f"⚠️ Không thể mở file {OUTPUT_FILE}: {e}")
        f = None
    
    try:
        log_and_print(f"\n=== AI-Enhanced Schoof test (p = {bits}-bit, {n_curves} curves) ===", f)
        
        # Bước 1: Sinh tập data
        curves = generate_curves(bits, n_curves)
        
        if len(curves) == 0:
            log_and_print("⚠️ Không có curve nào được sinh!", f)
            return
        
        # Bước 2: Test list curves đã sinh
        stats = test_curves(curves, bits, f)
        
    except Exception as e:
        log_and_print(f"⚠️ Lỗi trong quá trình test: {e}", f)
    finally:
        # Đóng file
        if f is not None:
            f.close()


# ------------------------
# Entry
# ------------------------
if __name__ == "__main__":
    test_ai_vs_schoof(bits=BIT, n_curves=CURVES)
