

# This file was *autogenerated* from the file sage_schoof.sage
from sage.all_cmdline import *   # import sage library

_sage_const_512 = Integer(512); _sage_const_3 = Integer(3); _sage_const_256 = Integer(256); _sage_const_0p1 = RealNumber('0.1'); _sage_const_128 = Integer(128); _sage_const_0p15 = RealNumber('0.15'); _sage_const_64 = Integer(64); _sage_const_0p2 = RealNumber('0.2'); _sage_const_32 = Integer(32); _sage_const_16 = Integer(16); _sage_const_0p25 = RealNumber('0.25'); _sage_const_8 = Integer(8); _sage_const_0p3 = RealNumber('0.3'); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_2p5 = RealNumber('2.5'); _sage_const_2 = Integer(2); _sage_const_0p85 = RealNumber('0.85'); _sage_const_4 = Integer(4); _sage_const_0p5 = RealNumber('0.5'); _sage_const_100 = Integer(100); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41)
import time
import math
import numpy as np
from sage.all import EllipticCurve, GF, crt
from ai_predictor import TracePredictor

# ------------------------
# 1. AI Predictor
# ------------------------
# Sử dụng TracePredictor được huấn luyện trong ai_predictor để đảm bảo đồng nhất với pipeline training.

# ------------------------
# 2. Phiên bản Schoof cơ bản (rút gọn)
# ------------------------
def schoof_ai(E, p, t_interval=None):
    """
    Phiên bản đơn giản của Schoof, dùng AI-enhanced interval (t_hat ± delta)
    - E: EllipticCurve
    - p: prime field
    - t_interval: (t_min, t_max), optional, khoảng Hasse thu hẹp bởi AI
    """
    # Danh sách primes nhỏ dùng cho CRT
    primes = [_sage_const_2, _sage_const_3, _sage_const_5, _sage_const_7, _sage_const_11, 
              _sage_const_13, _sage_const_17, _sage_const_19, _sage_const_23, _sage_const_29, _sage_const_31, _sage_const_37, _sage_const_41]

    t_mod = []
    mod_list = []

    # Tính khoảng Hasse hoặc dùng khoảng AI với xử lý overflow
    if t_interval is None:
        # Full Hasse bound: [-2√p, 2√p]
        try:
            if hasattr(p, 'isqrt'):
                sqrt_p = int(p.isqrt())
            else:
                # Xử lý overflow khi convert p sang int
                try:
                    p_int = int(p)
                    sqrt_p = int(math.isqrt(p_int))
                except (OverflowError, ValueError):
                    # Fallback: ước lượng từ bit_length
                    p_bits = p.bit_length() if hasattr(p, 'bit_length') else 256
                    sqrt_p = int(2**(p_bits // 2))
        except Exception:
            # Ultimate fallback
            p_bits = p.bit_length() if hasattr(p, 'bit_length') else 256
            sqrt_p = int(2**(p_bits // 2))
        
        try:
            t_min, t_max = -2 * sqrt_p, 2 * sqrt_p
        except (OverflowError, ValueError):
            # Fallback: dùng giá trị an toàn
            t_min, t_max = -int(2**128), int(2**128)
    else:
        # Xử lý overflow khi convert t_interval
        try:
            t_min = int(t_interval[0])
            t_max = int(t_interval[1])
        except (OverflowError, ValueError):
            # Fallback: dùng giá trị từ interval trực tiếp (Sage integer)
            t_min, t_max = t_interval[0], t_interval[1]

    # Tính trace mod các primes nhỏ với xử lý overflow
    for ell in primes:
        try:
            # Tính trace mod ell
            # Cách 1: Dùng E.trace_of_frobenius() nếu có (chính xác nhất)
            if hasattr(E, 'trace_of_frobenius'):
                try:
                    trace_full = E.trace_of_frobenius()
                    # Xử lý overflow khi convert sang int
                    try:
                        t_ell = int(trace_full) % ell
                    except (OverflowError, ValueError):
                        # Fallback: dùng mod trực tiếp từ Sage integer
                        t_ell = int(trace_full % ell)
                except Exception:
                    # Fallback: tính từ cardinality
                    try:
                        order_full = E.cardinality()
                        # Xử lý overflow khi tính p + 1 - order
                        try:
                            p_val = int(p)
                            order_val = int(order_full)
                            t_ell = (p_val + 1 - order_val) % ell
                        except (OverflowError, ValueError):
                            # Fallback: dùng Sage integer
                            t_ell = int((p + 1 - order_full) % ell)
                    except Exception:
                        continue
            else:
                # Cách 2: Tính từ cardinality (chậm hơn nhưng chính xác)
                try:
                    order_full = E.cardinality()
                    try:
                        p_val = int(p)
                        order_val = int(order_full)
                        t_ell = (p_val + 1 - order_val) % ell
                    except (OverflowError, ValueError):
                        # Fallback: dùng Sage integer
                        t_ell = int((p + 1 - order_full) % ell)
                except Exception:
                    continue
            
            t_mod.append(t_ell)
            mod_list.append(ell)

            # Nếu tích mod > 2*width của interval, có thể dừng sớm
            # Tính width và M với xử lý overflow
            try:
                width = t_max - t_min
                # Tính M bằng cách nhân từng phần để tránh overflow
                M = 1
                for m in mod_list:
                    m_int = int(m)
                    # Kiểm tra overflow trước khi nhân
                    if M > (2**63 - 1) // m_int:  # Kiểm tra overflow cho int64
                        break
                    M *= m_int
                if M > 2 * width:
                    break
            except (OverflowError, ValueError):
                # Nếu overflow, tiếp tục với primes tiếp theo
                continue
        except Exception:
            continue

    if len(t_mod) == 0:
        # Fallback: dùng cardinality trực tiếp
        return int(E.cardinality())

    # CRT để hợp nhất t mod ell với xử lý overflow
    try:
        # Tính M với xử lý overflow
        M = 1
        for m in mod_list:
            m_int = int(m)
            # Kiểm tra overflow trước khi nhân
            try:
                if M > (2**63 - 1) // m_int:  # Kiểm tra overflow cho int64
                    # Nếu overflow, dùng Sage integer
                    M = Integer(M) * Integer(m_int)
                else:
                    M *= m_int
            except (OverflowError, ValueError):
                # Chuyển sang Sage integer
                M = Integer(M) * Integer(m_int)
        
        # Tính CRT
        try:
            t_crt = int(crt(t_mod, mod_list))
        except (OverflowError, ValueError):
            # Fallback: dùng Sage integer
            t_crt = crt(t_mod, mod_list)
            if hasattr(t_crt, '__int__'):
                try:
                    t_crt = int(t_crt)
                except (OverflowError, ValueError):
                    pass  # Giữ nguyên Sage integer
    except Exception:
        # Ultimate fallback: dùng cardinality trực tiếp
        return int(E.cardinality())

    # Tìm trace t trong khoảng [t_min, t_max] sao cho t ≡ t_crt (mod M)
    # t = t_crt + k*M, cần tìm k sao cho t_min <= t <= t_max
    # Xử lý overflow khi tính toán
    try:
        # Chuyển sang Sage integer nếu cần
        if isinstance(t_crt, (int, Integer)) and isinstance(M, (int, Integer)):
            t_crt_val = Integer(t_crt) if not isinstance(t_crt, Integer) else t_crt
            M_val = Integer(M) if not isinstance(M, Integer) else M
            t_min_val = Integer(t_min) if not isinstance(t_min, Integer) else t_min
            t_max_val = Integer(t_max) if not isinstance(t_max, Integer) else t_max
        else:
            t_crt_val = t_crt
            M_val = M
            t_min_val = t_min
            t_max_val = t_max
        
        # Tìm k sao cho t_min <= t_crt + k*M <= t_max
        # => (t_min - t_crt) / M <= k <= (t_max - t_crt) / M
        
        # Tính k gần nhất với xử lý overflow
        try:
            k_min = (t_min_val - t_crt_val) // M_val
            k_max = (t_max_val - t_crt_val) // M_val
        except (OverflowError, ValueError):
            # Fallback: dùng Sage integer division
            k_min = (t_min_val - t_crt_val) // M_val
            k_max = (t_max_val - t_crt_val) // M_val
        
        # Thử các giá trị k trong khoảng [k_min, k_max]
        t = None
        try:
            k_range_start = int(k_min) - 1 if hasattr(k_min, '__int__') else int(k_min) - 1
            k_range_end = int(k_max) + 2 if hasattr(k_max, '__int__') else int(k_max) + 2
        except (OverflowError, ValueError):
            # Nếu không convert được, dùng giá trị nhỏ hơn
            k_range_start = -100
            k_range_end = 100
        
        # Giới hạn range để tránh quá lớn
        if k_range_end - k_range_start > 1000:
            # Nếu range quá lớn, chỉ thử một số giá trị quanh trung tâm
            try:
                center_k = int((k_min + k_max) // 2) if hasattr((k_min + k_max) // 2, '__int__') else 0
                k_range_start = center_k - 10
                k_range_end = center_k + 10
            except Exception:
                k_range_start = -10
                k_range_end = 10
        
        # Đảm bảo range hợp lệ cho Python range()
        k_range_start = max(-1000, min(k_range_start, 1000))
        k_range_end = max(-1000, min(k_range_end, 1000))
        
        for k in range(k_range_start, k_range_end + 1):
            try:
                # Chuyển k sang Sage integer nếu cần
                k_val = Integer(k) if isinstance(M_val, Integer) else k
                t_candidate = t_crt_val + k_val * M_val
                if t_min_val <= t_candidate <= t_max_val:
                    t = t_candidate
                    break
            except (OverflowError, ValueError):
                continue
        
        # Nếu không tìm thấy, chọn giá trị gần nhất
        if t is None:
            # Chọn k sao cho t_crt + k*M gần trung tâm của khoảng nhất
            try:
                center = (t_min_val + t_max_val) // 2
                k = (center - t_crt_val) // M_val
                t = t_crt_val + k * M_val
                # Đảm bảo t trong khoảng
                while t < t_min_val:
                    t += M_val
                while t > t_max_val:
                    t -= M_val
            except (OverflowError, ValueError):
                # Ultimate fallback: dùng cardinality
                return int(E.cardinality())
        
        # Clip vào khoảng nếu vẫn ngoài (safety check)
        t = max(t_min_val, min(t, t_max_val))
        
    except Exception:
        # Ultimate fallback: dùng cardinality
        return int(E.cardinality())

    # Tính order từ trace với xử lý overflow
    try:
        p_val = int(p) if hasattr(p, '__int__') else p
        t_val = int(t) if hasattr(t, '__int__') else t
        order = p_val + 1 - t_val
        return int(order) if hasattr(order, '__int__') else order
    except (OverflowError, ValueError):
        # Fallback: dùng Sage integer
        try:
            order = p + 1 - t
            return int(order) if hasattr(order, '__int__') else order
        except Exception:
            # Ultimate fallback: dùng cardinality
            return int(E.cardinality())


AI_WEIGHTS_PATH = '018new_weights.hdf5'

N_MC_SAMPLES = 1

# ------------------------
# 3. Chạy thử nghiệm
# ------------------------
def test_ai_vs_schoof(bits=_sage_const_64 ):
    print(f"\n=== AI-Enhanced Schoof test (p = {bits}-bit) ===")
    p = random_prime(_sage_const_2 **bits - _sage_const_1 , lbound=_sage_const_2 **(bits-_sage_const_1 ))
    a = randint(_sage_const_1 , p-_sage_const_1 )
    b = randint(_sage_const_1 , p-_sage_const_1 )
    start = time.time()
    E = EllipticCurve(GF(p), [a, b])
    

    # --- baseline ---
    print("🔹 Baseline Schoof...")
    order1 = E.cardinality()
    t1 = time.time() - start
    print(f"⏱️ Time: {t1:.4f}s")

    # --- AI-enhanced ---
    # Truyền bit_size để normalize đúng (model được train với 128-bit)
    print("\n🔹 AI-enhanced Schoof...")
    t1_ai = time.time()
    ai_model = TracePredictor(AI_WEIGHTS_PATH, bit_size=bits)
    t_hat, delta = ai_model.predict_trace(p, a, b, n_samples=N_MC_SAMPLES)
    interval = (t_hat - delta, t_hat + delta)
    order2 = schoof_ai(E, p, t_interval=interval)
    t2_ai = time.time() - t1_ai
    print(f"⏱️ Time: {t2_ai:.4f}s (reduced search width)")

    # Tính trace thực tế
    trace_real = int(p + 1 - order1)
    
    # So sánh kết quả
    print(f"\nTrace thực tế: {trace_real}")
    print(f"Trace AI dự đoán: {t_hat}")
    print(f"Sai số trace: {abs(trace_real - t_hat)}")
    print(f"Khoảng Hasse AI: {interval}")
    print(f"Trace có trong khoảng AI? {interval[0] <= trace_real <= interval[1]}")
    print(f"Thời gian giảm: {((t1 - t2_ai) / t1) * 100:.1f}%")
    print(f"Order(E) base: {order1}")
    print(f"Order(E) AI  : {order2}")
    print(f"Chênh lệch: {order1 - order2}")
    print(f"p: {p}")
    print(f"a: {a}")
    print(f"b: {b}")


# ------------------------
# Entry
# ------------------------
if __name__ == "__main__":
    test_ai_vs_schoof(bits=128)
