

# This file was *autogenerated* from the file sage_schoof.sage
from sage.all_cmdline import *   # import sage library

_sage_const_512 = Integer(512); _sage_const_3 = Integer(3); _sage_const_256 = Integer(256); _sage_const_0p1 = RealNumber('0.1'); _sage_const_128 = Integer(128); _sage_const_0p15 = RealNumber('0.15'); _sage_const_64 = Integer(64); _sage_const_0p2 = RealNumber('0.2'); _sage_const_32 = Integer(32); _sage_const_16 = Integer(16); _sage_const_0p25 = RealNumber('0.25'); _sage_const_8 = Integer(8); _sage_const_0p3 = RealNumber('0.3'); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_2p5 = RealNumber('2.5'); _sage_const_2 = Integer(2); _sage_const_0p85 = RealNumber('0.85'); _sage_const_4 = Integer(4); _sage_const_0p5 = RealNumber('0.5'); _sage_const_100 = Integer(100); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41)
import time
import math
import numpy as np
from sage.all import EllipticCurve, GF, crt
from ai_predictor import TracePredictor

# ------------------------
# 1. AI Predictor
# ------------------------
# Sử dụng TracePredictor được huấn luyện trong ai_predictor để đảm bảo đồng nhất với pipeline training.

# ------------------------
# 2. Phiên bản Schoof cơ bản (rút gọn)
# ------------------------
def schoof_ai(E, p, t_interval=None):
    """
    Phiên bản đơn giản của Schoof, dùng AI-enhanced interval (t_hat ± delta)
    - E: EllipticCurve
    - p: prime field
    - t_interval: (t_min, t_max), optional, khoảng Hasse thu hẹp bởi AI
    """
    # Danh sách primes nhỏ dùng cho CRT
    primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41]

    t_mod = []
    mod_list = []

    # Nếu không có t_interval, sử dụng full Hasse
    if t_interval is None:
        # Tính sqrt_p với xử lý overflow cho số lớn (256-bit)
        # Sử dụng Sage's isqrt hoặc math.isqrt nếu có
        try:
            # Thử dùng Sage integer square root (chính xác và không overflow)
            if hasattr(p, 'isqrt'):
                sqrt_p_int = int(p.isqrt())
            elif hasattr(math, 'isqrt'):
                sqrt_p_int = math.isqrt(int(p))
            else:
                # Fallback: tính từ float
                sqrt_p_float = float(np.sqrt(float(p)))
                if np.isfinite(sqrt_p_float):
                    sqrt_p_int = int(sqrt_p_float)
                else:
                    # Fallback: ước lượng từ log2
                    p_log2 = math.log2(int(p)) if isinstance(p, (int, Integer)) else math.log2(float(p))
                    sqrt_p_int = int(np.exp2(p_log2 / 2.0))
        except (OverflowError, ValueError, TypeError):
            # Fallback: ước lượng từ bit_length
            try:
                p_bits = p.bit_length() if hasattr(p, 'bit_length') else 256
                sqrt_p_int = int(2**(p_bits // 2))
            except Exception:
                # Ultimate fallback: dùng giá trị mặc định
                sqrt_p_int = int(2**128)  # Giá trị mặc định cho 256-bit
        t_min, t_max = -2 * sqrt_p_int, 2 * sqrt_p_int
    else:
        t_min, t_max = t_interval

    for ell in primes:
        try:
            # trace mod ell (Sage đã có hàm chính xác)
            t_ell = E.trace_of_frobenius() % ell
            t_mod.append(int(t_ell))
            mod_list.append(ell)

            # Nếu tích mod > 2*width của interval, có thể dừng sớm
            width = t_max - t_min
            # Tính tích mod_list với xử lý overflow
            try:
                product = np.prod(mod_list, dtype=np.int64)
                if product > 2 * width:
                    break
            except (OverflowError, ValueError):
                # Fallback: tính tích bằng cách nhân từng phần
                try:
                    product = 1
                    for m in mod_list:
                        product *= int(m)
                        if product > 2 * width:
                            break
                    if product > 2 * width:
                        break
                except Exception:
                    # Nếu vẫn overflow, tiếp tục với primes tiếp theo
                    continue
        except Exception:
            continue

    # CRT để hợp nhất t mod ell
    t = crt(t_mod, mod_list)

    # Thu gọn trace về khoảng [-p, p]
    if t > p:
        t -= p
    # Nếu có t_interval, thu gọn về khoảng
    t = max(t_min, min(t, t_max))

    order = int(p + 1 - t)
    return order


AI_WEIGHTS_PATH = '018new_weights.hdf5'

N_MC_SAMPLES = 10

# ------------------------
# 3. Chạy thử nghiệm
# ------------------------
def test_ai_vs_schoof(bits=_sage_const_64 ):
    print(f"\n=== AI-Enhanced Schoof test (p = {bits}-bit) ===")
    # Tính 2^bits với xử lý overflow
    try:
        if bits <= 128:
            p_max = int(_sage_const_2 **bits - _sage_const_1 )
            p_min = int(_sage_const_2 **(bits-_sage_const_1 ))
        else:
            # Với bits > 128, dùng cách tính an toàn hơn
            p_max = int(2**bits - 1) if bits <= 1024 else None
            p_min = int(2**(bits-1)) if bits <= 1024 else None
            if p_max is None or p_min is None:
                # Fallback: dùng Sage integer
                p_max = _sage_const_2 **bits - _sage_const_1 
                p_min = _sage_const_2 **(bits-_sage_const_1 )
    except Exception:
        # Fallback: dùng Sage integer
        p_max = _sage_const_2 **bits - _sage_const_1 
        p_min = _sage_const_2 **(bits-_sage_const_1 )
    
    p = random_prime(p_max, lbound=p_min)
    a = randint(_sage_const_1 , p-_sage_const_1 )
    b = randint(_sage_const_1 , p-_sage_const_1 )
    start = time.time()
    E = EllipticCurve(GF(p), [a, b])
    
    # Tính bit_size thực tế của p để normalize đúng
    try:
        p_bits = p.bit_length() if hasattr(p, 'bit_length') else bits
    except Exception:
        p_bits = bits
    
    try:
        # Truyền bit_size để normalize đúng (dùng bit_size thực tế của p)
        ai_model = TracePredictor(AI_WEIGHTS_PATH, bit_size=p_bits)
    except FileNotFoundError as exc:
        print(f"⚠️ Không tìm thấy weights AI: {exc}")
        return

    # --- baseline ---
    print("🔹 Baseline Schoof...")
    order1 = E.cardinality()
    t1 = time.time() - start
    print(f"⏱️ Time: {t1:.4f}s")

    # --- AI-enhanced ---
    print("\n🔹 AI-enhanced Schoof...")
    t1_ai = time.time()
    t_hat, delta = ai_model.predict_trace(p, a, b, n_samples=N_MC_SAMPLES)
    interval = (t_hat - delta, t_hat + delta)
    order2 = schoof_ai(E, p, t_interval=interval)
    t2_ai = time.time() - t1_ai
    print(f"⏱️ Time: {t2_ai:.4f}s (reduced search width)")

    # Tính trace thực tế với xử lý overflow
    try:
        trace_real = int(p + 1 - order1)
    except (OverflowError, ValueError):
        # Fallback: tính từng phần
        try:
            trace_real = int(p) + 1 - int(order1)
        except Exception:
            # Ultimate fallback: dùng Sage integer
            trace_real = p + 1 - order1
            if hasattr(trace_real, '__int__'):
                trace_real = int(trace_real)
    
    # So sánh kết quả với xử lý overflow
    print(f"\nTrace thực tế: {trace_real}")
    print(f"Trace AI dự đoán: {t_hat}")
    
    # Tính sai số trace với xử lý overflow
    try:
        trace_error = abs(int(trace_real) - int(t_hat))
    except (OverflowError, ValueError):
        try:
            trace_error = abs(trace_real - t_hat)
            if hasattr(trace_error, '__int__'):
                trace_error = int(trace_error)
        except Exception:
            trace_error = "N/A (overflow)"
    print(f"Sai số trace: {trace_error}")
    
    print(f"Khoảng Hasse AI: {interval}")
    
    # Kiểm tra trace có trong khoảng AI với xử lý overflow
    try:
        in_interval = int(interval[0]) <= int(trace_real) <= int(interval[1])
    except (OverflowError, ValueError):
        try:
            in_interval = interval[0] <= trace_real <= interval[1]
        except Exception:
            in_interval = "N/A (overflow)"
    print(f"Trace có trong khoảng AI? {in_interval}")
    
    # Tính thời gian giảm
    try:
        time_reduction = ((t1 - t2_ai) / t1) * 100 if t1 > 0 else 0
        print(f"Thời gian giảm: {time_reduction:.1f}%")
    except Exception:
        print(f"Thời gian giảm: N/A")
    
    print(f"Order(E) base: {order1}")
    print(f"Order(E) AI  : {order2}")
    
    # Tính chênh lệch với xử lý overflow
    try:
        order_diff = int(order1) - int(order2)
    except (OverflowError, ValueError):
        try:
            order_diff = order1 - order2
            if hasattr(order_diff, '__int__'):
                order_diff = int(order_diff)
        except Exception:
            order_diff = "N/A (overflow)"
    print(f"Chênh lệch: {order_diff}")
    
    print(f"p: {p}")
    print(f"a: {a}")
    print(f"b: {b}")


# ------------------------
# Entry
# ------------------------
if __name__ == "__main__":
    test_ai_vs_schoof(bits=64)
